# Generated by Django 2.1.5 on 2019-02-07 08:17

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Город')),
                ('variations', models.CharField(max_length=1000, verbose_name='Вариации названия города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название лота')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание лота')),
                ('date', models.DateField(verbose_name='Дата добавления лота')),
                ('modifatedate', models.DateField(blank=True, null=True, verbose_name='Дата изменения лота')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
                ('lastprice', models.CharField(blank=True, max_length=10, verbose_name='Предыдущая цена лота')),
                ('lot_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на лот')),
                ('vk_page_id', models.IntegerField(blank=True, null=True, verbose_name='ID страницы лота')),
                ('vk_album_id', models.IntegerField(blank=True, null=True, verbose_name='ID альбома с лотом')),
                ('vk_owner_id', models.IntegerField(blank=True, null=True, verbose_name='ID владельца группы')),
                ('vk_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID владельца лота')),
                ('forwarding', models.CharField(choices=[('not', 'не указано'), ('yes', 'да'), ('no', 'нет')], default='not', max_length=5, verbose_name='Возможность пересыла')),
                ('tags_temp', models.CharField(blank=True, max_length=500, null=True, verbose_name='ТЕСТОВЫЕ теги')),
                ('city_temp', models.CharField(blank=True, max_length=30, null=True, verbose_name='ТЕСТОВЫЕ города')),
                ('visible', models.BooleanField(default=False, null=True, verbose_name='Видимость')),
                ('moderated', models.BooleanField(default=False, null=True, verbose_name='Прошел модерацию')),
                ('ondelete', models.BooleanField(default=False, null=True, verbose_name='На удаление')),
                ('marked_spam', models.IntegerField(default='0', null=True, verbose_name='Помечено как Спам')),
                ('marked_bad_category', models.IntegerField(default='0', null=True, verbose_name='Помечено как неверная категория')),
                ('marked_soldout', models.IntegerField(default='0', null=True, verbose_name='Помечено как продано')),
                ('marked_insult', models.IntegerField(default='0', null=True, verbose_name='Помечено как оскорбление')),
                ('vk_image_tumb_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL tumbnail изображения')),
                ('vk_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('vk_image_host', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL хоста изображения')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Подкатегория товара',
                'verbose_name_plural': 'Подкатегории товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('vk_user_id', models.IntegerField(null=True, verbose_name='ID пользователя VK')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['pk'],
            },
        ),
    ]
